### ISSUE TITLE
交易驗證碼取消

### ISSUE THREAD

**Issue by jsnprofessor** [ECPay/ECPayPaymentGatewayKit_Android#1]
### [ 問題描述 ]
OTP 交易驗證碼那個頁面選取消會回傳 `CallbackStatus.Success`

### [ 操作步驟 ]
1. 呼叫 `PaymentkitManager.createPayment` 建立訂單
2. 輸入完測試資料點選 `確認付款`
3. 進入交易驗證碼點選 `取消(Cancel)`

**Comment by adelachang0418** [comment]
您好，感謝您的提問
CallbackStatus回傳的狀態代表SDK[執行]狀態，無論交易成功或失敗皆會回傳[執行成功]
進入銀行3D交易驗證碼時，點選取消(Cancel)屬於[交易狀態]，需判斷回傳的[RtnCode]
當[RtnCode]不等於1時，代表[交易失敗]

如有其他疑問，可連絡技術客服信箱：techsupport@ecpay.com.tw
感謝您
